      common/inputvar/ tf,dtout,gam,n,nnopt,nav,alpha,beta,eta2,ngr,
     $     xgrmax,xgrmin,ygrmax,ygrmin,zgrmax,zgrmin,xgrlim,ygrlim,
     $     zgrlim,hmin,hmax,nrelax,trelax,sep0,qdar,amns,rns,rp,vpeak,
     $     treloff,ngravrad,sol
      real tf,dtout,gam,alpha,beta,eta2,
     $     xgrmax,xgrmin,ygrmax,ygrmin,zgrmax,zgrmin,xgrlim,ygrlim,
     $     zgrlim,hmin,hmax,trelax,sep0,qdar,amns,rns,rp,vpeak,
     $     treloff,sol
      integer n,nnopt,nav,ngr,nrelax,ngravrad
